name: zarcoteam
favicon: null
layout_spectrum: 0.50335
typography_spectrum: 0.65917
title: 'ZARCO TEAM '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#414143'
    - '#e69c52'
    - '#c4c4c4'
    - '#9e9e9f'
  brandStrength: 0.8384702026378363
  lightness: 0.5079952175728977
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
